routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['web', 'auth.shop', 'billable']], function () {
    /* App Installation */
    Route::get('/','Dashboard\DashboardController@index')->name('home');

    Route::group(['prefix'=>'setup','as' => 'setup.'], function () {
        Route::get('/','Setup\SetupController@index')->name('index');
        Route::get('/steps','Setup\SetupController@steps')->name('steps');
        Route::get('uninstall/view','Setup\SetupController@unInstallView')->name('uninstall.view');
        Route::post('store','Setup\SetupController@store')->name('store');
        Route::post('uninstall','Setup\SetupController@unInstall')->name('uninstall');
    });

    Route::group(['prefix'=>'offers','as' => 'offers.'], function () {
        Route::get('/','Offer\OfferController@index')->name('index');
        Route::get('/getProducts','Offer\OfferController@getProducts')->name('getProducts');
        Route::get('create','Offer\OfferController@create')->name('create');
        Route::get('{ruleset}/edit','Offer\OfferController@edit')->name('edit');
        Route::post('{ruleset}/status','Offer\OfferController@status')->name('status');
        Route::post('/','Offer\OfferController@store')->name('store');
        Route::post('/check','Offer\OfferController@check')->name('check');
        Route::post('{ruleset}','Offer\OfferController@update')->name('update');
        Route::delete('{ruleset}/delete','Offer\OfferController@delete')->name('delete');
        Route::delete('delete-product','Offer\OfferController@deleteProduct')->name('deleteProduct');
    });

    Route::group(['prefix'=>'settings','as' => 'settings.'], function () {
        Route::get('/','Display\DisplaySettingsController@index')->name('index');
        Route::post('store','Display\DisplaySettingsController@store')->name('store');
        Route::post('restore','Display\DisplaySettingsController@restore')->name('restore');
    });

    Route::get('plan-pricing','Frontend\CommonController@planPricing')->name('plan_pricing');
    Route::get('faq','Frontend\CommonController@faq')->name('faq');
    Route::get('instruction','Frontend\CommonController@instruction')->name('instruction');
    Route::get('manual-install','Frontend\CommonController@manualInstall')->name('manual.install');
    Route::get('terms-of-use','Frontend\CommonController@termsandcondition')->name('termsandcondition');
    Route::get('privacy-policy','Frontend\CommonController@privacyPolicy')->name('privacy_policy');
});

/**
 * Frontend
 */


Route::get('flush', function(){
    request()->session()->flush();
});

/*Route::get('test', function(){
    foreach (config('rocket') as $key => $val){
        //dd(json_decode($val['text_settings'],1));
        $entity = new \App\Models\DisplaySetting;
        $entity->shop_id = null;
        $entity->display_type = $key;
        $entity->type = json_decode($val['type']);
        $entity->text_settings = json_decode($val['text_settings']);
        $entity->style_settings = json_decode($val['style_settings']);
        $entity->button_settings = json_decode($val['button_settings']);
        $entity->updated_at = null;
        $entity->save(['timestamps' => false]);

    }
});*/


Route::get('/webhooks/', 'WebHookController@get');
Route::get('/webhooks/delete', 'WebHookController@destroy');

app/Http/Controllers/Setup/SetupController.php
<?php

namespace App\Http\Controllers\Setup;

use App\Models\Webhook;
use App\Notifications\ContactAdminNotification;
use App\Notifications\ContactUsNotification;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use OhMyBrew\ShopifyApp\ShopifyApp;

class SetupController extends Controller
{
    public $view = 'pages.setup.';

    public function steps(){

        $shop = \ShopifyApp::shop();

        $is_new_theme = false;
        if($shop->theme_id) {
            $main_theme = $shop->theme_id;
        } else {
            $main_theme = $shop->api()->rest('GET', 'admin/themes.json',['role' => 'main']);
            $main_theme = $main_theme->body->themes[0]->id;
            $is_new_theme = true;
        }

        $data = $this->index();
        $orders = Webhook::where('shop_id',$shop->id)->where('topic','orders/create')->count();

        return view($this->view.'steps',compact('data','orders','main_theme', 'is_new_theme'));
    }

    public function index() {
        $shop = \ShopifyApp::shop();
        $themes = $shop->api()->rest('GET', 'admin/themes.json', ['fields' => 'id,name']);
        $theme = $data = [];
        foreach($themes->body->themes as $val){
            $theme['label'] = $val->name;
            $theme['value'] = (string)$val->id;
            $data[] = $theme;
        }
        return $data;
    }

    public function store(Request $request) {

        if($request->filled('call_type')) {
            $shop = \ShopifyApp::shop();
            $user = new User();

            $user->email = $shop->email_id;
            $request->merge(['assigned_id' => time()]);
            \Notification::send($user,new ContactUsNotification($request->all()));
            $user->email = config('mail.from.address');
            \Notification::send($user,new ContactAdminNotification($request->all()));

            return \Response::json([
                'data' => 'Mail Sucessfully Send',
            ], 200);
        }


        $template = "sections/cart-template.liquid";
        $shop = \ShopifyApp::shop();
        $asset = $shop->api()->rest('GET', 'admin/themes/'.$request->theme.'/assets.json',["asset[key]" => $template]);

        if($asset->errors) {
            $template = "snippets/ajax-cart-template.liquid";
            $asset = $shop->api()->rest('GET', 'admin/themes/'.$request->theme.'/assets.json',["asset[key]" => $template]);
        }

        if($asset->errors) {
            $template = "templates/cart.liquid";
            $asset = $shop->api()->rest('GET', 'admin/themes/'.$request->theme.'/assets.json',["asset[key]" => $template]);
        }

        if(@$asset->body->asset){
            $asset = $asset->body->asset->value;

            if(strpos($asset ,"uninstall-crawlappscartitemprice")){
                $asset = str_replace('uninstall-crawlappscartitemprice',"crawlapps-cart-item-price ",$asset);
            }
            elseif(!strpos($asset ,"<span class='crawlapps-cart-item-price'")){
                $asset = str_replace('{{ item.price | money }}',"<span class='crawlapps-cart-item-price ' data-key='{{item.key}}'>{{ item.price | money }}</span>",$asset);

                $asset = str_replace('{{ item.original_price | money }}',"<span class='crawlapps-cart-item-price ' data-key='{{item.key}}'>{{ item.original_price | money }}</span>",$asset);
            }

            if(strpos($asset ,"uninstall-crawlappscartitemlineprice")){
                $asset = str_replace('uninstall-crawlappscartitemlineprice',"crawlapps-cart-item-line-price ",$asset);
            }
            elseif(!strpos($asset ,"<span class='crawlapps-cart-item-line-price'")){
                $asset = str_replace('{{ item.line_price | money }}',"<span class='crawlapps-cart-item-line-price' data-key='{{item.key}}'>{{ item.line_price | money }}</span>",$asset);
                $asset= str_replace('{{ item.original_line_price | money }}',"<span class='crawlapps-cart-item-line-price' data-key='{{item.key}}'>{{ item.original_line_price | money }}</span>",$asset);
            }

            if(!strpos($asset ,"value=\"{{ item.quantity }}\" data-key='{{item.key}}'")){
                $asset = str_replace("value=\"{{ item.quantity }}\"","value=\"{{ item.quantity }}\" data-key='{{item.key}}'",$asset);
            }

            if(strpos($asset ,"uninstall-crawlappscartoriginaltotal")){
                $asset = str_replace('uninstall-crawlappscartoriginaltotal',"crawlapps-cart-original-total ",$asset);
            }
            elseif(!strpos($asset ,"<span class='crawlapps-cart-original-total'")){
                $asset = str_replace('{{ cart.total_price | money }}',"<span class='crawlapps-cart-original-total'>{{ cart.total_price | money }}</span>",$asset);
            }

            $parameter['asset']['key'] = $template;
            $parameter['asset']['value'] = $asset;
            $asset = $shop->api()->rest('PUT', 'admin/themes/'.$request->theme.'/assets.json',$parameter);

            $this->snippet('add',$request);
            $this->updateThemeLiquid('add',$request);
            if(@$asset->body->asset) {

                $shop->css_theme = $request->css_theme;
                $shop->theme_id = $request->theme;
                $shop->save();

                return \Response::json([
                    'is_new_theme' => false,
                    'theme_id' => $shop->theme_id,
                    'data' => 'Auto Install Completed',
                ], 200);
            }

        }
    }

    public function updateThemeLiquid($type,$request){
        $shop = \ShopifyApp::shop();
        if($type == 'add'){

            $asset = $shop->api()->rest('GET', 'admin/themes/'.$request->theme.'/assets.json',["asset[key]" => 'layout/theme.liquid']);
            if(@$asset->body->asset) {
                $asset = $asset->body->asset->value;
                if(!strpos($asset ,"{% include 'crawlapps-offers' %}</head>")) {
                    $asset = str_replace('</head>',"{% include 'crawlapps-offers' %}</head> ",$asset);
                }

                $parameter['asset']['key'] = 'layout/theme.liquid';
                $parameter['asset']['value'] = $asset;
                $asset = $shop->api()->rest('PUT', 'admin/themes/'.$request->theme.'/assets.json',$parameter);
            }
        }
    }

    public function snippet($type,$request){

        $shop = \ShopifyApp::shop();
        if($type == 'add') {
            $value = <<<EOF
        <script id="crawlapps_offer_shop_data" type="application/json">
            {
                "shop": {
                    "domain": "{{ shop.domain }}",
                    "permanent_domain": "{{ shop.permanent_domain }}",
                    "url": "{{ shop.url }}",
                    "secure_url": "{{ shop.secure_url }}",
                    "money_format": {{ shop.money_format | json }},
                    "currency": {{ shop.currency | json }}
                },
                "customer": {
                    "id": {{ customer.id | json }},
                    "tags": {{ customer.tags | json }}
                },
                "cart": {{ cart | json }},
                "template": "{{ template | split: "." | first }}",
                "product": {{ product | json }},
                "collection": {{ collection.products | json }}
            }
        </script>
EOF;
        }
        $parameter['asset']['key'] = 'snippets/crawlapps-offers.liquid';
        $parameter['asset']['value'] = $value;
        $asset = $shop->api()->rest('PUT', 'admin/themes/'.$request->theme.'/assets.json',$parameter);
    }

    public function unInstallView(Request $request){
        $shop = \ShopifyApp::shop();

        $is_new_theme = true;
        $main_theme = null;
        if ($shop->theme_id) {
            $main_theme = $shop->theme_id;
            $is_new_theme = false;
        }else{
            $main_theme = $shop->api()->rest('GET', 'admin/themes.json',['role' => 'main']);
            $main_theme = $main_theme->body->themes[0]->id;
        }

        $data = $this->index();
        return view($this->view.'uninstall',compact('data','main_theme', 'is_new_theme'));
    }

    public function unInstall(Request $request){
        $shop = \ShopifyApp::shop();

        $template = "sections/cart-template.liquid";
        $asset = $shop->api()->rest('GET', 'admin/themes/'.$request->theme.'/assets.json',["asset[key]" => $template]);

        if($asset->errors) {
            $template = "snippets/ajax-cart-template.liquid";
            $asset = $shop->api()->rest('GET', 'admin/themes/'.$request->theme.'/assets.json',["asset[key]" => $template]);
        }

        if($asset->errors) {
            $template = "templates/cart.liquid";
            $asset = $shop->api()->rest('GET', 'admin/themes/'.$request->theme.'/assets.json',["asset[key]" => $template]);
        }

        if(@$asset->body->asset) {

            $asset = $asset->body->asset->value;
            if(strpos($asset ,"crawlapps-cart-item-price")) {
                $asset = str_replace('crawlapps-cart-item-price',"uninstall-crawlappscartitemprice ",$asset);
            }

            if(strpos($asset ,"crawlapps-cart-item-line-price")) {
                $asset = str_replace('crawlapps-cart-item-line-price',"uninstall-crawlappscartitemlineprice ",$asset);
            }

            if(strpos($asset ,"crawlapps-cart-original-total")) {
                $asset = str_replace('crawlapps-cart-original-total',"uninstall-crawlappscartoriginaltotal ",$asset);
            }

            $parameter['asset']['key'] = $template;
            $parameter['asset']['value'] = $asset;

            $asset = $shop->api()->rest('PUT', 'admin/themes/'.$request->theme.'/assets.json',$parameter);
            if(@$asset->body->asset){
                $shop->theme_id = null;
                $shop->save();

                $main_theme = $shop->api()->rest('GET', 'admin/themes.json',['role' => 'main']);

resources/views/pages/setup/index.blade.php
@extends('layouts.app')
@section("content")

    <setup-index-component
        props-url = "{{
                json_encode([
                        "index" => route("setup.index"),
                        "store" => route("setup.store"),
                ],JSON_HEX_APOS)
                }}"
        props-trans = "{{ json_encode([],JSON_HEX_APOS)}}"
        props-data = "{{ json_encode(
                [
                    'theme'=> $data,
                    'cssthemeOption'=> collect(config('css_theme'))->sort()->all(),
                    'css_theme'=> \ShopifyApp::shop()->css_theme
                ],JSON_HEX_APOS)}}"
    ></setup-index-component>
@endsection

resources/views/pages/setup/popup.blade.php
@section('popup')
    <div id="app-popup" class="app-popup d-none" v-show="showPopup">
        <div class="overlay"></div>
        <div class="app-popup-box">
            <div class="app-popup-header">
                <h6>Setup</h6>
                <a href="#" class="close-icon" v-on:click="setupPopup"><i class="ion ion-ios-close"></i></a>
            </div>
            <div class="app-popup-body">
                <setup-index-component></setup-index-component>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/setup/steps.blade.php
@extends('layouts.app')
@section("content")
    <div class="oa-main">
            <div class="oa-row">
                <div class="w-60 mb-xs-20">
                    <div class="d-flex align-items-center justify-content-center h-100">
                        <img src="/images/svg/Welcome.svg" style="height: 100%;width: 100%;"/>
                    </div>
                </div>
                <div class="w-40">
                    <h2 class="mb-3 text-center">Let's get you started. Your next steps are :</h2>
                    <div class="oa-box mb-20" style="min-height: auto;">
                        <div class="oa-box-body text-center">
                            <div class="cricle mb-1">1</div>
                            <p class="mb-0">Setup Rocket Discount in your theme</p>
                            <div class="d-flex justify-content-end"><a href="#" v-on:click="setupPopup" class="text-gray-700"><i class="ion ion-ios-arrow-round-forward h1"></i></a></div>
                        </div>
                    </div>
                    <div class="oa-box mb-20" style="min-height: auto;">
                        <div class="oa-box-body text-center">
                            <div class="cricle mb-1">2</div>
                            <p class="mb-0">Create your first Rocket Discount Ruleset. </p>
                            <div class="d-flex justify-content-end"><a href="{{ route('offers.create') }}" class="text-gray-700"><i class="ion ion-ios-arrow-round-forward h1"></i></a></div>
                        </div>
                    </div>
                    <div class="oa-box mb-20" style="min-height: auto;">
                        <div class="oa-box-body text-center">
                            <div class="cricle mb-1">3</div>
                            <p class="mb-0">Visit the Display Settings to customize how your discount will be displayed for your customers.</p>
                            <div class="d-flex justify-content-end"><a href="{{ route('settings.index') }}"  class="text-gray-700"><i class="ion ion-ios-arrow-round-forward h1"></i></a></div>
                        </div>
                    </div>
                </div>
                <div class="w-100">
                    <div class="oa-box mb-20" style="min-height: auto;">
                        <div class="oa-box-header">
                            <div class="d-flex align-items-center justify-content-between">
                                <h2 class="text-primary">Important Notes :</h2>
                            </div>
                        </div>
                        <div class="oa-box-body">
                            <ul class="mb-20" style="padding-left: 15px;">
                                <li class="font-size-lg">
                                    For optimal experience. Keep your theme name the same as provided by your theme developer. That way, we can detect the exact theme you are using and install custom CSS for your specific theme.
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
    </div>
    <div class="oa-footer">
        <div class="text-center">
            <need-help></need-help>
        </div>
    </div>
<div id="app-popup" class="app-popup d-none" style="display:none" v-show="showPopup">
    <div class="overlay"></div>
    <div class="popup-container border-radius">
        <div class="popup-head popup-head-new">
            <img src="https://cdn.shopify.com/s/files/1/0055/4093/7792/files/icon.png?v=1584376349"/>
            <div class="popup-heading-text">
                <h3 class="main-head">Get Started with Rocket Discount</h3>
                <p>Not sure how to get started with Rocket Discount? Here is a step-by-step guide to help you on your way:</p>
                <p>First, we need to install Rocket Discount to your theme. For that, we have three types of installation methods.</p>
            </div>
            <div class="close position-absolute">
                <a href="#" class="close-icon" v-on:click="setupPopup"><i class="ion ion-ios-close"></i></a>
            </div>
        </div>
        <div class="popup-body">

                <div class="popup-row">

                    <div class="popup-row-item">
                        <div class="install-option install-option-new border-radius">
                            <div class="fancy-heading">
                                <h4>Expert Install</h4> <font style="color:#fff;"> (Advanced Users Only) </font>

                            </div>
                            <div class="logo">
                                <img src="/images/svg/expert_install.svg" />
                            </div>
                            <div class="content">
                                <div class="tooltip-width-text">
                                Hire our team of experts to install the app for you and ensure that it works as expected in your store. (Comes with a $25 USD flat fee).
                                </div>
                            </div>
                            <div class="first-step-btn">
                                <button class="btn btn-block" v-on:click="contact2Popup" >Contact</button>
                            </div>
                        </div>
                    </div>

                    <div class="popup-row-item">
                        <div class="install-option install-option-new border-radius">
                            <div class="fancy-heading">
                                <h4>Auto Install</h4> <font style="color:#fff;"> (Most Popular) </font>
                            </div>
                            <div class="logo">
                                <img src="/images/svg/auto_install.svg" />
                            </div>
                            <div class="content">
                                <div class="tooltip-width-text">
                                    Allow us to install all relevant code to your store automatically. This method works for most stores, but for some, it might not install it properly. We recommend that you do this in a duplicated version of your current theme, that is not yet published.
                                </div>
                            </div>
                            <div class="first-step-btn">
                                <button v-on:click="show2Popup" class="btn btn-block">Start Now</button>
                            </div>
                        </div>
                    </div>

                    <div class="popup-row-item">
                        <div class="install-option install-option-new">
                            <div class="fancy-heading">
                                <h4>Manual Install</h4> <font style="color:#fff;"> (Hassle–Free) </font>

                            </div>
                            <div class="logo">
                                <img src="/images/svg/manual.svg" />
                            </div>
                            <div class="content">

                                <div class="tooltip-width-text">
                                    Manually install the code needed for Rocket Discount to function. If you are comfortable with installing code on your own, go with this. We recommend that you do this in a duplicated version of your current theme, that is not yet published.
                                </div>
                            </div>
                            <div class="first-step-btn">
                                <a href="{{route('faq') }}" class="btn btn-block">Installation Guide</a>
                            </div>
                        </div>
                    </div>

                </div>
        </div>
    </div>
</div>

<div class="automatic_install_section d-none" id="app-popup-install" style="display:none" v-show="showInstallPopup">
<div class="overlay"></div>
    <div class="automatic_install_popup">
    <div class="close position-absolute">
        <a href="#" id="close" v-on:click="show2Popup" class="cancel font-weight-bold d-block text-center text-body">×</a>
    </div>
    <div class="install_section-text">

        <setup-index-component
            props-url = "{{
                json_encode([
                        "index" => route("setup.index"),
                        "store" => route("setup.store"),
                ],JSON_HEX_APOS)
                }}"
            props-trans = "{{ json_encode([],JSON_HEX_APOS)}}"
            props-data = "{{ json_encode([
            'theme'=> $data,
            'main_theme'=> $main_theme,
            'is_new_theme'=> $is_new_theme,
            'cssthemeOption'=> collect(config('css_theme'))->sort()->all(),
             'css_theme'=> \ShopifyApp::shop()->css_theme
            ],JSON_HEX_APOS)}}"
        ></setup-index-component>
    </div>
    </div>
</div>

<div class="automatic_install_section d-none" id="contact-app-popup-install" style="display:none" v-show="contactInstallPopup">
    <div class="overlay"></div>
    <div class="automatic_install_popup">
        <div class="close position-absolute">
            <a href="#" id="close" v-on:click="contact2Popup" class="cancel font-weight-bold d-block text-center text-body">×</a>
        </div>
        <div class="install_section-text">
            <contact-index-component
                props-url = "{{
            json_encode([
                    "index" => route("setup.index"),
                    "store" => route("setup.store"),
            ],JSON_HEX_APOS)
            }}"
                props-trans = "{{ json_encode([],JSON_HEX_APOS)}}"
                props-data = "{{ json_encode([
        'theme'=> $data,
        'main_theme'=> $main_theme,
        'is_new_theme'=> $is_new_theme,
        ],JSON_HEX_APOS)}}"
            ></contact-index-component>
        </div>
    </div>
</div>

@endsection

resources/views/pages/setup/uninstall.blade.php
@extends('layouts.app')
@section("content")
    <uninstall-component
        props-url = "{{
                            json_encode([
                                    "index" => route("setup.index"),
                                    "uninstall" => route("setup.uninstall"),
                                    "store" => route("setup.store"),
                            ],JSON_HEX_APOS)
                            }}"
        props-trans = "{{ json_encode([],JSON_HEX_APOS)}}"
        props-data = "{{ json_encode([
            'theme'=> $data,
            'main_theme' => $main_theme,
            'is_new_theme' => $is_new_theme

            ],JSON_HEX_APOS)}}"
    ></uninstall-component>
@endsection